// Shared immutable artwork catalogue. No database IDs or external image URLs.
export const DECOR_CATALOG = [
  { id: "armchair", label: "포근한 안락의자", category: "거실", width: 22, height: 28, sprite: 0 },
  { id: "coffee_table", label: "원목 티 테이블", category: "거실", width: 22, height: 28, sprite: 1 },
  { id: "floor_cushion", label: "세이지 방석", category: "거실", width: 22, height: 28, sprite: 2 },
  { id: "dresser", label: "원목 서랍장", category: "거실", width: 22, height: 28, sprite: 3 },
  { id: "wardrobe", label: "큰 옷장", category: "거실", width: 22, height: 28, sprite: 4 },
  { id: "standing_mirror", label: "전신 거울", category: "거실", width: 22, height: 28, sprite: 5 },
  { id: "fridge", label: "민트 냉장고", category: "주방", width: 22, height: 28, sprite: 6 },
  { id: "sink_counter", label: "싱크대", category: "주방", width: 22, height: 28, sprite: 7 },
  { id: "stove", label: "오븐 레인지", category: "주방", width: 22, height: 28, sprite: 8 },
  { id: "dining_table", label: "둥근 식탁", category: "주방", width: 22, height: 28, sprite: 9 },
  { id: "dining_chair", label: "분홍 식탁 의자", category: "주방", width: 22, height: 28, sprite: 10 },
  { id: "stool", label: "나무 스툴", category: "주방", width: 22, height: 28, sprite: 11 },
  { id: "tulip_planter", label: "튤립 화단", category: "정원", width: 22, height: 28, sprite: 12 },
  { id: "sunflower_planter", label: "해바라기 화분", category: "정원", width: 22, height: 28, sprite: 13 },
  { id: "hedge", label: "초록 생울타리", category: "정원", width: 22, height: 28, sprite: 14 },
  { id: "fence", label: "나무 울타리", category: "정원", width: 22, height: 28, sprite: 15 },
  { id: "garden_arch", label: "덩굴 아치", category: "정원", width: 22, height: 28, sprite: 16 },
  { id: "garden_bench", label: "정원 벤치", category: "정원", width: 22, height: 28, sprite: 17 },
  { id: "stepping_stone", label: "돌 디딤판", category: "정원", width: 22, height: 28, sprite: 18 },
  { id: "pond", label: "수련 연못", category: "정원", width: 22, height: 28, sprite: 19 },
  { id: "fountain", label: "작은 분수", category: "정원", width: 22, height: 28, sprite: 20 },
  { id: "birdhouse", label: "새들의 집", category: "정원", width: 22, height: 28, sprite: 21 },
  { id: "mailbox", label: "빨간 우편함", category: "정원", width: 22, height: 28, sprite: 22 },
  { id: "string_lights", label: "반짝 전구 울타리", category: "정원", width: 22, height: 28, sprite: 23 },
  { id: "tent", label: "숲속 텐트", category: "캠핑", width: 22, height: 28, sprite: 24 },
  { id: "picnic_blanket", label: "피크닉 돗자리", category: "캠핑", width: 22, height: 28, sprite: 25 },
  { id: "camp_chair", label: "캠핑 의자", category: "캠핑", width: 22, height: 28, sprite: 26 },
  { id: "campfire", label: "모닥불", category: "캠핑", width: 22, height: 28, sprite: 27 },
  { id: "cooler", label: "파란 아이스박스", category: "캠핑", width: 22, height: 28, sprite: 28 },
  { id: "hammock", label: "낮잠 해먹", category: "캠핑", width: 22, height: 28, sprite: 29 },
  { id: "books", label: "알록달록 책 더미", category: "취미", width: 22, height: 28, sprite: 30 },
  { id: "toy_robot", label: "블록 로봇", category: "취미", width: 22, height: 28, sprite: 31 },
  { id: "teddy_bear", label: "곰 인형", category: "취미", width: 22, height: 28, sprite: 32 },
  { id: "easel", label: "그림 이젤", category: "취미", width: 22, height: 28, sprite: 33 },
  { id: "piano", label: "작은 피아노", category: "취미", width: 22, height: 28, sprite: 34 },
  { id: "aquarium", label: "물고기 수족관", category: "취미", width: 22, height: 28, sprite: 35 },
] as const;
export type DecorId = (typeof DECOR_CATALOG)[number]['id'];
export const DECOR_CATEGORIES = ['전체', '거실', '주방', '정원', '캠핑', '취미'] as const;
export function isBuiltinDecor(id: string): boolean { return DECOR_CATALOG.some(item => `builtin:${item.id}` === id); }
